### PR TITLE
Add information regarding MathML Friend application via email.

### PR DESCRIPTION
**Pull request by fred-wang**

### CODE REVIEW

**Comment by physikerwelt** [comment]
:+1:

**Comment by physikerwelt** [comment]
Is is OK if I merge this?

**Comment by fred-wang** [comment]
This can be merged if we all agree about using email for Friends applications and about the fact that the Friends mailing list is public.

**Comment by rgaiacs** [comment]
@fred-wang are you OK to make the friends mailing list invitation only? People send the email requesting be one friend and we accept s/he and add s/he to the mailing list. We could have one announcements public list for people that just want the announcements but not want to be friends.

**Comment by fred-wang** [comment]
I'm not sure I understand the question. Is it possible to:
- Make the list public: anyone can read the archive and post a message.
- But people who are not subscribed to the list have their message moderated before publication.

**Comment by rgaiacs** [comment]
> Is it possible to:
> 
>    Make the list public: anyone can read the archive and post a message.
>    But people who are not subscribed to the list have their message moderated before publication.

**Yes**.

> I'm not sure I understand the question.

I'm thinking of why someone will ask to be Friend if they could just subscribe to the list.

**Comment by fred-wang** [comment]
> I'm thinking of why someone will ask to be Friend if they could just subscribe to the list.

cf http://mathml-association.org/legal-documents/affiliates.html

Friends are just an easy status to show support for the MathML Association & mission. The mailing list subscription is totally orthogonal to the Friends status, I'm just use proposing to use the public mailing list to retrieve their application for now.

**Pull request closed without merging**
