### PR TITLE
FAQ: Reorganize the question about the plans for native MathML and me…

### PR DESCRIPTION
**Pull request by fred-wang**
…ntion the "MathML in HTML5" draft.

### CODE REVIEW

**Comment by kohlhase** [comment]
I do not think we should mention this in the FAQ until we have coordinated more to the MathWG. On the contrary, I think we should retract this pull request, so that nobody accidentally merges it.

**Comment by fred-wang** [comment]
OK I deleted the public repo and removed the public link for now. That's a shame since I used it to discuss with potential partners, but if that can avoid misunderstanding...

**Comment by fred-wang** [comment]
@kohlhase I reopened the pull request and renamed the document. Do you think we can merge it now?

**Comment by kohlhase** [comment]
Yes, I think that would be appropriate.

**Pull request merged**
