### PR TITLE
Remove the ambiguous "accepted by the board" and replace it with a de…

### PR DESCRIPTION
**Pull request by fred-wang**
…lay of one week before minutes publication.

### CODE REVIEW

**Comment by fred-wang** [comment]
@r-gaia-cs these should not be merged before we approved it at the board meeting

**Comment by rgaiacs** [comment]
@fred-wang sorry for that. Next time could you add a note mention that it can only be merge after the board meeting? If you add WIP, "work in progress", on the subject/title I will not merge the pull request.

**Comment by fred-wang** [comment]
I thought you read the discussion elsewhere.

**Comment by rgaiacs** [comment]
> I thought you read the discussion elsewhere.

I read it but forgot it when checking the pull requests. =(

**Comment by fred-wang** [comment]
I reopened the pull requests. Please do not merge :-)

**Pull request merged**
