### PR TITLE
Add information regarding MathML Friend application via email.

### PR DESCRIPTION
**Pull request by fred-wang**
This version does not require any mailing list for application.

### CODE REVIEW

**Comment by kohlhase** [comment]
I concur, we should merge this now. Well done.

**Comment by physikerwelt** [comment]
:+1:

**Comment by fred-wang** [comment]
@dginev @rgaiacs : any objection to merging this?

**Comment by dginev** [comment]
merge away

**Comment by rgaiacs** [comment]
@fred-wang Done: http://mathml-association.org/affiliates/friends.html

**Pull request merged**
